Site:
  - Language: "en"
    ShortTitle: Arctic Biodiversity Map
    LongTitle: Long-term changes in Arctic biodiversity - a systematic map
    Subtitle: Help shape our research
    IntroText: Some introductory text
  - Language: "ru"
    ShortTitle: Карта биоразнообразия Арктики
    LongTitle: Долгосрочные изменения биоразнообразия Арктики - систематическая карта
    Subtitle: Помогите сформировать наше исследование
    IntroText: Некоторый вводный текст

Languages: [ "en-GB", "ru-RU", "fi-FI", "nb-NO", "is-IS", "fr-CA", "sv-SE" ]

Translations:
  - It: Loading...
    In: fi
    Is: Loading...
  - It: OpenConsultation
    In: fi
    Is: Open Consultations
